#include <algorithm>
#include <initializer_list>
#include <string>
#include <string_view>
#include <utility>

#include "activity_sdk_lua_artifacts_internal.h"

namespace sunrise::client::content::activity::sdk_generation::lua_artifacts::internal {
namespace {

using Field = std::pair<std::string_view, std::string_view>;

void sort_keys(Value::Object& value) {
    std::sort(value.begin(), value.end(), [](const auto& first, const auto& second) {
        return first.first < second.first;
    });
}

[[nodiscard]] Value field_map(std::initializer_list<Field> source) {
    Value::Object output;
    output.reserve(source.size());
    for (const auto& [name, type] : source) {
        output.push_back({std::string(name), string(type)});
    }
    sort_keys(output);
    return object(std::move(output));
}

/** Appends the seven declared name lanes for one field prefix. */
void append_name_fields(Value::Object& output, std::string_view prefix) {
    const auto add = [&output, prefix](std::string_view suffix, std::string_view type) {
        std::string name(prefix);
        name.append(suffix);
        output.push_back({std::move(name), string(type)});
    };
    add("_name", "string_or_nil");
    add("_name_provenance", "unresolved_package_inline_package_path_or_identifier_candidate");
    add("_name_provenance_code", "u32");
    add("_name_candidate_count", "u32");
    add("_name_source_tag", "u32");
    add("_name_source_class", "u32");
    add("_name_strongest_tier_overflow", "boolean");
}

/** Builds one view's declared fields, expanding each prefix into its name lanes. */
[[nodiscard]] Value named_view(std::initializer_list<Field> source,
                               std::initializer_list<std::string_view> prefixes,
                               std::string_view rowScope) {
    Value::Object fields;
    fields.reserve(source.size() + prefixes.size() * 7U);
    for (const auto& [name, type] : source) {
        fields.push_back({std::string(name), string(type)});
    }
    for (const std::string_view prefix : prefixes) {
        append_name_fields(fields, prefix);
    }
    sort_keys(fields);
    return object({
        {"fields", object(std::move(fields))},
        {"immutable", boolean(true)},
        {"row_scope", string(rowScope)},
        {"stale_read", string("throws")},
    });
}

[[nodiscard]] Value view(std::initializer_list<Field> fields, std::string_view rowScope) {
    return object({
        {"fields", field_map(fields)},
        {"immutable", boolean(true)},
        {"row_scope", string(rowScope)},
        {"stale_read", string("throws")},
    });
}

} // namespace

/** Appends the core world view declarations to the contract object. */
void append_world_core_views(Value::Object& output) {
    output.push_back(
        {"WorldView",
         view({{"scenario_tag", "u32"},
               {"scenario_name", "string"},
               {"sdk_build_sha256", "hex_sha256"},
               {"sdk_payload_sha256", "hex_sha256"},
               {"source_fingerprint", "hex_sha256"},
               {"manifest_payload_sha256", "hex_sha256"},
               {"shard_payload_sha256", "hex_sha256"},
               {"bubbles", "WorldRowCollection<WorldBubbleView>"},
               {"states", "WorldRowCollection<WorldStateView>"},
               {"objects", "WorldRowCollection<WorldObjectView>"},
               {"slots", "WorldRowCollection<WorldSlotView>"},
               {"descriptors", "WorldRowCollection<WorldDescriptorView>"},
               {"embedded_placement_links", "WorldRowCollection<WorldEmbeddedPlacementLinkView>"},
               {"authored_placements", "WorldRowCollection"},
               {"embedded_placements", "WorldRowCollection"},
               {"typed_references", "WorldRowCollection<WorldTypedReferenceView>"},
               {"container_placement_lists", "WorldRowCollection<WorldContainerPlacementListView>"},
               {"container_placement_owners",
                "WorldRowCollection<WorldContainerPlacementOwnerView>"},
               {"container_placements", "WorldRowCollection"},
               {"container_placement_configs",
                "WorldRowCollection<WorldContainerPlacementConfigView>"},
               {"container_placement_components",
                "WorldRowCollection<WorldContainerPlacementComponentView>"},
               {"type23_placement_links", "WorldRowCollection<WorldType23PlacementLinkView>"},
               {"type23_placement_candidates",
                "WorldRowCollection<WorldType23PlacementCandidateView>"},
               {"static_spatial_tables", "WorldRowCollection<WorldStaticSpatialTableView>"},
               {"static_spatial_owners", "WorldRowCollection<WorldStaticSpatialOwnerView>"},
               {"static_spatial_instances", "WorldRowCollection"},
               {"trigger_volume_tables", "WorldRowCollection<WorldTriggerVolumeTableView>"},
               {"trigger_volume_owners", "WorldRowCollection<WorldTriggerVolumeOwnerView>"},
               {"trigger_volume_incoming_references",
                "WorldRowCollection<WorldTriggerVolumeIncomingReferenceView>"},
               {"trigger_volumes", "WorldRowCollection"},
               {"trigger_volume_vertices", "WorldRowCollection<WorldGlobalTriggerVertexView>"},
               {"trigger_volume_triangles", "WorldRowCollection<WorldGlobalTriggerTriangleView>"},
               {"names", "WorldRowCollection<WorldNameView>"},
               {"tag_names", "WorldRowCollection<WorldTagNameView>"},
               {"name_candidates", "WorldRowCollection<WorldNameCandidateView>"},
               {"inline_name_candidates", "WorldRowCollection<WorldInlineNameCandidateView>"},
               {"authored_squad_config_contexts",
                "WorldRowCollection<WorldAuthoredSquadConfigContextView>"},
               {"authored_squad_placement_contexts",
                "WorldRowCollection<WorldAuthoredSquadPlacementContextView>"},
               {"authored_squad_point_contexts",
                "WorldRowCollection<WorldAuthoredSquadPointContextView>"},
               {"authored_squad_point_placement_matches",
                "WorldRowCollection<WorldAuthoredSquadPointPlacementMatchView>"},
               {"authored_squad_edge_contexts",
                "WorldRowCollection<WorldAuthoredSquadEdgeContextView>"},
               {"diagnostics", "WorldDiagnosticsView"},
               {"coverage", "WorldCoverageCollection"}},
              "exact_activity_and_scenario_generation")});
    output.push_back({"WorldVectorView",
                      view({{"count", "u32"},
                            {"x", "real32"},
                            {"y", "real32_or_nil"},
                            {"z", "real32_or_nil"},
                            {"w", "real32_or_nil"}},
                           "copied_row_value")});
    output.push_back({"SquadAnchorView",
                      view({{"id", "string"},
                            {"world_id", "string"},
                            {"row", "u32_1_based_global_pack"},
                            {"collection_row", "u32_1_based_scenario"},
                            {"squad_row", "u32_1_based_scenario"},
                            {"point_ordinal", "u32_0_based"},
                            {"object_list_tag", "u32"},
                            {"placement_ordinal", "u32_0_based"},
                            {"flags", "u32"},
                            {"placed_entry_identity", "u64_decimal_string"},
                            {"position", "WorldVectorView_3"}},
                           "bound_scenario_squad_anchor")});
    output.push_back({"WorldBubbleView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"name_hash", "u32"},
                                  {"first_state_row", "u32_1_based_or_nil"},
                                  {"state_count", "u32"},
                                  {"name_row", "u32_1_based_or_nil"},
                                  {"index", "u32_0_based"},
                                  {"is_public", "boolean"}},
                                 {"selected"},
                                 "generated_world.bubbles")});
    output.push_back({"WorldStateView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"state_hash", "u32"},
                                  {"raw_u32_at_12", "u32"},
                                  {"entry_tag", "u32"},
                                  {"registry_tag", "u32"},
                                  {"slice_set_index", "u32_0_based"},
                                  {"map_bubble_index", "u32_0_based"},
                                  {"bubble_row", "u32_1_based_or_nil"},
                                  {"name_row", "u32_1_based_or_nil"},
                                  {"entry_name_row", "u32_1_based_or_nil"},
                                  {"registry_name_row", "u32_1_based_or_nil"},
                                  {"index", "u32_0_based"},
                                  {"enabled", "boolean"},
                                  {"resolved", "boolean"}},
                                 {"selected", "entry", "registry"},
                                 "generated_world.states")});
    output.push_back({"WorldObjectView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"bubble_row", "u32_1_based_or_nil"},
                                  {"state_row", "u32_1_based_or_nil"},
                                  {"registry_tag", "u32"},
                                  {"object_tag", "u32"},
                                  {"registry_key", "u32"},
                                  {"first_slot_row", "u32_1_based_or_nil"},
                                  {"slot_count", "u32"},
                                  {"config_count", "u32"},
                                  {"placed_subblock_count", "u32"},
                                  {"placed_leaf_count", "u32"},
                                  {"placed_hop_count", "u32"},
                                  {"bare_target_count", "u32"},
                                  {"replicated_placement_count", "u32"},
                                  {"object_index", "u32_0_based"},
                                  {"registry_name_row", "u32_1_based_or_nil"},
                                  {"object_name_row", "u32_1_based_or_nil"},
                                  {"registry_descriptor", "u16"},
                                  {"safety", "group_safety_or_nil"},
                                  {"safety_code", "u32"},
                                  {"complete", "boolean"}},
                                 {"registry", "object"},
                                 "generated_world.objects")});
    output.push_back({"WorldSlotView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"object_row", "u32_1_based_or_nil"},
                                  {"name_hash", "u32"},
                                  {"name_row", "u32_1_based_or_nil"},
                                  {"first_descriptor_row", "u32_1_based_or_nil"},
                                  {"descriptor_count", "u32"},
                                  {"slot_index", "u16"},
                                  {"slot_type", "u16"}},
                                 {"selected"},
                                 "generated_world.slots")});
    output.push_back({"WorldDescriptorView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"slot_row", "u32_1_based_or_nil"},
                                  {"config_tag", "u32"},
                                  {"component_class", "u32"},
                                  {"sense_schema", "u32"},
                                  {"auth_schema", "u32"},
                                  {"descriptor_offset", "u32"},
                                  {"bubble_index", "u32_0_based"},
                                  {"config_name_row", "u32_1_based_or_nil"},
                                  {"placement_identifier", "u64_decimal_string"},
                                  {"placement_link_row", "u32_1_based_or_nil"},
                                  {"embedded_placement_link_row", "u32_1_based_or_nil"},
                                  {"placement_identifier_read", "boolean"}},
                                 {"config"},
                                 "generated_world.descriptors")});
    output.push_back({"WorldEmbeddedPlacementLinkView",
                      view({{"id", "string"},
                            {"row", "u32_1_based_shard_section"},
                            {"descriptor_row", "u32_1_based_or_nil"},
                            {"slot_row", "u32_1_based_or_nil"},
                            {"object_row", "u32_1_based_or_nil"},
                            {"first_candidate_row", "u32_1_based_or_nil"},
                            {"candidate_count", "u32"},
                            {"declared_placement_count", "u64_decimal_string"},
                            {"array_data_offset", "u64_decimal_string"},
                            {"complete", "boolean"}},
                           "generated_world.embedded_placement_links")});
    output.push_back({"WorldTypedReferenceView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"source_object_row", "u32_1_based_or_nil"},
                                  {"source_slot_row", "u32_1_based_or_nil"},
                                  {"source_config_tag", "u32"},
                                  {"source_offset", "u32"},
                                  {"target_object_row", "u32_1_based_or_nil"},
                                  {"target_key", "u32"},
                                  {"target_slot_index", "u16"},
                                  {"target_slot_type", "u16"},
                                  {"source_config_name_row", "u32_1_based_or_nil"},
                                  {"join", "reference_join_or_nil"},
                                  {"join_code", "u32"}},
                                 {"source_config"},
                                 "generated_world.typed_references")});
    output.push_back({"WorldAuthoredPlacementView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"source_object_row", "u32_1_based_or_nil"},
                                  {"bubble_row", "u32_1_based_or_nil"},
                                  {"state_row", "u32_1_based_or_nil"},
                                  {"declared_bubble_index", "i32"},
                                  {"object_list_tag", "u32"},
                                  {"class_list_tag", "u32"},
                                  {"entry_index", "u32_0_based"},
                                  {"object_list_name_row", "u32_1_based_or_nil"},
                                  {"class_list_name_row", "u32_1_based_or_nil"},
                                  {"source_offset", "u64_decimal_string"},
                                  {"rotation_bits_x", "u32"},
                                  {"rotation_bits_y", "u32"},
                                  {"rotation_bits_z", "u32"},
                                  {"rotation_bits_w", "u32"},
                                  {"position_bits_x", "u32"},
                                  {"position_bits_y", "u32"},
                                  {"position_bits_z", "u32"},
                                  {"uniform_scale", "real32"},
                                  {"uniform_scale_bits", "u32"},
                                  {"name_hash", "u32"},
                                  {"placement_flags_raw", "u32"},
                                  {"identifier", "u64_decimal_string"},
                                  {"auxiliary_relative", "i64_decimal_string"},
                                  {"context", "string_or_nil"},
                                  {"context_code", "u32"},
                                  {"rotation", "WorldVectorView_4"},
                                  {"position", "WorldVectorView_3"}},
                                 {"object_list", "class_list"},
                                 "generated_world.authored_placements")});
    output.push_back({"WorldEmbeddedPlacementView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"link_row", "u32_1_based_or_nil"},
                                  {"entry_index", "u32_0_based"},
                                  {"source_offset", "u64_decimal_string"},
                                  {"class_list_tag", "u32"},
                                  {"class_list_name_row", "u32_1_based_or_nil"},
                                  {"name_hash", "u32"},
                                  {"identifier", "u64_decimal_string"},
                                  {"auxiliary_relative", "i64_decimal_string"},
                                  {"auxiliary_offset", "u64_decimal_string"},
                                  {"fourth_lane", "real32"},
                                  {"replication_byte", "u8"},
                                  {"gameworld_byte", "u8"},
                                  {"object_type", "u8"},
                                  {"has_auxiliary", "boolean"},
                                  {"object_type_read", "boolean"},
                                  {"rotation", "WorldVectorView_4"},
                                  {"position", "WorldVectorView_3"}},
                                 {"class_list"},
                                 "generated_world.embedded_placements")});
    output.push_back({"WorldContainerPlacementView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"list_row", "u32_1_based"},
                                  {"object_list_tag", "u32"},
                                  {"resource_tag", "u32"},
                                  {"resource_class", "u32"},
                                  {"entry_index", "u32_0_based"},
                                  {"class_list_tag", "u32"},
                                  {"class_list_name_row", "u32_1_based_or_nil"},
                                  {"first_config_row", "u32_1_based_or_nil"},
                                  {"config_count", "u32"},
                                  {"placement_identifier", "u64_decimal_string"},
                                  {"uniform_scale", "real32"},
                                  {"object_type", "u8"},
                                  {"resource_field_read", "boolean"},
                                  {"resource_resolved", "boolean"},
                                  {"list_complete", "boolean"},
                                  {"placement_identifier_read", "boolean"},
                                  {"complete", "boolean"},
                                  {"rotation", "WorldVectorView_4"},
                                  {"position", "WorldVectorView_3"}},
                                 {"object_list", "resource", "class_list"},
                                 "generated_world.container_placements")});
    output.push_back({"WorldContainerPlacementListView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"object_list_tag", "u32"},
                                  {"resource_tag", "u32"},
                                  {"resource_class", "u32"},
                                  {"object_list_name_row", "u32_1_based_or_nil"},
                                  {"resource_name_row", "u32_1_based_or_nil"},
                                  {"resource_field_read", "boolean"},
                                  {"resource_resolved", "boolean"},
                                  {"complete", "boolean"}},
                                 {"object_list", "resource"},
                                 "generated_world.container_placement_lists")});
    output.push_back({"WorldContainerPlacementOwnerView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"list_row", "u32_1_based_or_nil"},
                                  {"container_tag", "u32"},
                                  {"member_index", "u32_0_based"},
                                  {"container_name_row", "u32_1_based_or_nil"},
                                  {"scenario_bubble_mask", "u64_decimal_string"},
                                  {"map_bubble_mask", "hex_32_bytes"},
                                  {"context", "spatial_context_or_nil"},
                                  {"context_code", "u32"}},
                                 {"container"},
                                 "generated_world.container_placement_owners")});
    output.push_back({"WorldContainerPlacementConfigView",
                      named_view({{"id", "string"},
                                  {"row", "u32_1_based_shard_section"},
                                  {"placement_row", "u32_1_based_or_nil"},
                                  {"config_tag", "u32"},
                                  {"config_name_row", "u32_1_based_or_nil"},
                                  {"first_component_row", "u32_1_based_or_nil"},
                                  {"component_count", "u32"},
                                  {"build_ordinal", "u32_0_based"},
                                  {"second_word", "u32"},
                                  {"third_word", "u32"},
                                  {"complete", "boolean"}},
                                 {"config"},
                                 "generated_world.container_placement_configs")});
    output.push_back({"WorldContainerPlacementComponentView",
                      view({{"id", "string"},
                            {"row", "u32_1_based_shard_section"},
                            {"config_row", "u32_1_based_or_nil"},
                            {"component_class", "u32"},
                            {"first_word", "u32"},
                            {"second_word", "u32"},
                            {"fourth_word", "u32"},
                            {"ordinal", "u32_0_based"}},
                           "generated_world.container_placement_components")});
    output.push_back({"WorldType23PlacementLinkView",
                      view({{"id", "string"},
                            {"row", "u32_1_based_shard_section"},
                            {"descriptor_row", "u32_1_based_or_nil"},
                            {"slot_row", "u32_1_based_or_nil"},
                            {"first_candidate_row", "u32_1_based_or_nil"},
                            {"candidate_count", "u32"},
                            {"identity_match_count", "u32"},
                            {"active_candidate_count", "u32"},
                            {"resolved_candidate_row", "u32_1_based_or_nil"},
                            {"placement_identifier", "u64_decimal_string"},
                            {"join", "reference_join_or_nil"},
                            {"join_code", "u32"},
                            {"complete", "boolean"}},
                           "generated_world.type23_placement_links")});
    output.push_back({"WorldType23PlacementCandidateView",
                      view({{"id", "string"},
                            {"row", "u32_1_based_shard_section"},
                            {"link_row", "u32_1_based_or_nil"},
                            {"placement_row", "u32_1_based_or_nil"},
                            {"owner_row", "u32_1_based_or_nil"},
                            {"applicable_owner_count", "u32"}},
                           "generated_world.type23_placement_candidates")});
    output.push_back({"WorldAuthoredSquadConfigContextView",
                      view({{"id", "string"},
                            {"row", "u32_1_based_shard_section"},
                            {"global_row", "u32_1_based_or_nil"},
                            {"scenario_row", "u32_1_based_or_nil"},
                            {"config_tag", "u32"},
                            {"occurrence_row", "u32_1_based_or_nil"},
                            {"object_row", "u32_1_based_or_nil"},
                            {"path_ordinal", "u32_0_based"},
                            {"declared_bubble_index", "i32"},
                            {"spawner_row", "u32_1_based_or_nil"},
                            {"rule_row", "u32_1_based_or_nil"},
                            {"complete", "boolean"}},
                           "generated_world.authored_squad_config_contexts")});
    output.push_back({"WorldAuthoredSquadPlacementContextView",
                      view({{"id", "string"},
                            {"row", "u32_1_based_shard_section"},
                            {"global_row", "u32_1_based_or_nil"},
                            {"scenario_row", "u32_1_based_or_nil"},
                            {"occurrence_row", "u32_1_based_or_nil"},
                            {"object_list_tag", "u32"},
                            {"placement_ordinal", "u32_0_based"},
                            {"placed_entry_identity", "u64_decimal_string"},
                            {"position_bits_x", "u32"},
                            {"position_bits_y", "u32"},
                            {"position_bits_z", "u32"},
                            {"object_row", "u32_1_based_or_nil"},
                            {"path_ordinal", "u32_0_based"},
                            {"declared_bubble_index", "i32"},
                            {"actor_definition_tag", "u32_or_nil"},
                            {"source_offset", "u64_decimal_string"},
                            {"rotation_bits_x", "u32"},
                            {"rotation_bits_y", "u32"},
                            {"rotation_bits_z", "u32"},
                            {"rotation_bits_w", "u32"},
                            {"uniform_scale_bits", "u32"},
                            {"name_hash", "u32"},
                            {"placement_flags_raw", "u32"},
                            {"auxiliary_relative", "i64_decimal_string"},
                            {"complete", "boolean"}},
                           "generated_world.authored_squad_placement_contexts")});
    output.push_back({"WorldAuthoredSquadPointContextView",
                      view({{"id", "string"},
                            {"row", "u32_1_based_shard_section"},
                            {"global_row", "u32_1_based_or_nil"},
                            {"scenario_row", "u32_1_based_or_nil"},
                            {"point_row", "u32_1_based_or_nil"},
                            {"global_config_context_row", "u32_1_based_or_nil"},
                            {"config_context_row", "u32_1_based_or_nil"},
                            {"global_first_match_row", "u32_1_based_or_nil"},
                            {"first_match_row", "u32_1_based_or_nil"},
                            {"match_count", "u32"},
                            {"status", "point_context_status_or_nil"},
                            {"status_code", "u32"}},
                           "generated_world.authored_squad_point_contexts")});
    output.push_back({"WorldAuthoredSquadPointPlacementMatchView",
                      view({{"id", "string"},
                            {"row", "u32_1_based_shard_section"},
                            {"global_row", "u32_1_based_or_nil"},
                            {"scenario_row", "u32_1_based_or_nil"},
                            {"global_point_context_row", "u32_1_based_or_nil"},
                            {"point_context_row", "u32_1_based_or_nil"},
                            {"point_row", "u32_1_based_or_nil"},
                            {"global_config_context_row", "u32_1_based_or_nil"},
                            {"config_context_row", "u32_1_based_or_nil"},
                            {"global_placement_context_row", "u32_1_based_or_nil"},
                            {"placement_context_row", "u32_1_based_or_nil"},
                            {"placed_entry_identity", "u64_decimal_string"},
                            {"same_occurrence", "boolean"}},
                           "generated_world.authored_squad_point_placement_matches")});
    output.push_back({"WorldAuthoredSquadEdgeContextView",
                      view({{"id", "string"},
                            {"row", "u32_1_based_shard_section"},
                            {"global_row", "u32_1_based_or_nil"},
                            {"scenario_row", "u32_1_based_or_nil"},
                            {"edge_row", "u32_1_based_or_nil"}},
                           "generated_world.authored_squad_edge_contexts")});
}

} // namespace sunrise::client::content::activity::sdk_generation::lua_artifacts::internal
